### ISSUE TITLE
Any plans to make bucklescript-tea-starter-kit a full sample app?

### ISSUE THREAD

**Issue by mrvicadai** [tcoopman/bucklescript-tea-starter-kit#4]
Hi @tcoopman I think this is a great project for folks new to the bucklescript-tea stack! I am wonder if you are willing to accept pull requests that integrates non-trivial applications (such as [realworld.io](https://github.com/gothinkster/realworld)) that demonstrates:

- How to use router
- How to organize directories
- How to interact with persistent storage
- Various design patterns

?

I am happy to work on this and send PRs upstream while learning bs-tea; but if you plan to keep the starter-kit plain and simple I'll totally understand that as well 😄

**Comment by tcoopman** [comment]
Hi, thanks for your interest. I'm not sure if having *non-trivial* applications is something that needs to go in a starter kit.

I'm not sure what's the best choice here, adding the examples to this repo or starting a new one. You can always start with creating a PR for this repo and if we see that it's better in  a different repo then that's a low effort change?

What do you think?

**Comment by mrvicadai** [comment]
Yea I think that's a good approach -- build something and we can see how it turns out. I'll close this issue for now until I build something working...
